version: "3.8"
services:
  frontend:
    build: ./untitled
    container_name: front
    ports:
      - '3000:3000'
    volumes:
      - ./untitled:/app
      - ./app/node_modules
  backend:
    build: ./fastApiProject
    container_name: back
    ports:
      - '8000:8000'
    volumes:
      - ./fastApiProject:/back